import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";

export const metadata = {
  title: "Warner Brothers Demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
